 # BEV-QA training config on Bench2Drive_Base + Chat-B2D.

model:
  arch: bevqa
  model_type: base
  encoder_model: bevdriver_encoder
  encoder_model_ckpt: /workspace/BEV-QA/weights/bevdriver/checkpoint_best.pth
  llm_model: /workspace/BEV-QA/weights/llama-7b
  load_pretrained: True
  freeze_vit: True
  max_txt_len: 64
  num_query_token: 32
  has_lora: True

datasets:
  bench2drive_chatb2d: # name of the dataset builder
    build_info:
      annotations:
        train:
          sensor_root: '/home/p112g22/minsu/Bench2Drive_Base'
          language_root: '/home/p112g22/minsu/Chat-B2D/chat-B2D/train'
          input_rgb_size: 224
          input_multi_view_size: 112
          input_lidar_size: 224
        val:
          sensor_root: '/home/p112g22/minsu/Bench2Drive_Base'
          language_root: '/home/p112g22/minsu/Chat-B2D/chat-B2D/val'
          input_rgb_size: 224
          input_multi_view_size: 112
          input_lidar_size: 224
        # Optional held-out test set (fill in actual paths before use).
        # When populated, enable via run.test_splits: ["test"] or
        # --options run.test_splits=[\"test\"] on the CLI.
        test:
          sensor_root: '/path/to/Bench2Drive_Base_test'
          language_root: '/path/to/Chat-B2D/chat-B2D/test'
          input_rgb_size: 224
          input_multi_view_size: 112
          input_lidar_size: 224

    # Optional: split the provided val set into val_dev / val_test
    # (ratios/size are applied after shuffling with the seed below).
    val_split:
      dev_ratio: 0.5  # or set dev_size: N to use an absolute count
      seed: 42

run:
  task: bevqa_drive

  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.06
  max_epoch: 100
  batch_size_train: 4
  batch_size_eval: 4
  num_workers: 4
  num_nodes: 1
  warmup_steps: 2000
  # Early stopping based on validation agg_metrics (loss for BEV-QA).
  # Set patience <= 0 to disable.
  early_stop_patience: 2
  early_stop_min_delta: 0.0
  # Use val_dev split for early stopping.
  early_stop_split: "val_dev"

  # Debug options: limit steps per epoch for quick smoke tests.
  # Set to null or omit when running full training.
  debug_max_train_iters: null
  debug_max_val_iters: null

  seed: 42
  output_dir: "out/bevqa"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  skip_generate: True
  train_splits: ["train"]
  # Use the derived dev split for validation; test_splits can use val_test or a real test set.
  valid_splits: ["val_dev"]
  test_splits: ["val_test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  find_unused_parameters: True
